image: octavenz/docker-pipeline-build:latest

definitions:
  services:
    docker:
      memory: 5122
    mariadb:
      image: mariadb:focal
      environment:
        MARIADB_USER: ss
        MARIADB_PASSWORD: ss
        MARIADB_DATABASE: silverstripe
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'

  steps:
    - step: &testSS4.9_PHP7.4
        name: Test Silverstripe 4.9 - PHP 7.4
        script:
          - cd envs/ss4.9/php7.4
          - cp .env.example .env
          - echo 'SS_REOAKO_API_KEY="$SS_REOAKO_API_KEY"' >> .env
          - cat ./.env
          - docker compose up --profile "development" -d
          - sleep 2
          - wget http://localhost/dev/build
          - sleep 10
          - wget http://localhost

        services:
          - docker
          - mariadb
        size: 2x # Double resources available for this step.

pipelines:
  default:
    # testing should occur on all branches so we can deal with test failures
    # before pushing code to more important branches like develop or master.
    - parallel:
      - step: *testSS4.9_PHP7.4
      # - step: *testFrontend

